name: Run test and lint for Kamispy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install test requirements
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]
      - name: Lint with flake8
        run: flake8 . --count --show-source --statistics
      - name: Test with pytest
        run: pytest
      - name: Test with readme_renderer
        run: |
          python -m pip install readme_renderer
          python -m readme_renderer README.rst -o README.html
