"""empty message

Revision ID: 036a8aa4baab
Revises: 8e784b37271b
Create Date: 2023-09-05 10:37:25.299489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036a8aa4baab'
down_revision = '8e784b37271b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('food_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_unit', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
