"""empty message

Revision ID: 0de78946b9d2
Revises: 549249bc9c82
Create Date: 2023-09-04 16:10:45.184145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de78946b9d2'
down_revision = '549249bc9c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.alter_column('foodname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('food_category',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.alter_column('food_category',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('foodname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
