"""empty message

Revision ID: 250c945fda4b
Revises: 6d63df4d2e2d
Create Date: 2023-09-05 11:11:00.683658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250c945fda4b'
down_revision = '6d63df4d2e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_unit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('food_unit')

    # ### end Alembic commands ###
