"""empty message

Revision ID: 33a425586f5b
Revises: 0de78946b9d2
Create Date: 2023-09-04 16:19:38.685280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a425586f5b'
down_revision = '0de78946b9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.Integer(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=True))
        batch_op.drop_column('unit')
        batch_op.drop_column('food_price')

    # ### end Alembic commands ###
