"""empty message

Revision ID: 43922a66f76e
Revises: 33a425586f5b
Create Date: 2023-09-04 17:29:05.242576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43922a66f76e'
down_revision = '33a425586f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_unit', sa.Integer(), nullable=True))
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.INTEGER(), nullable=True))
        batch_op.drop_column('food_unit')

    # ### end Alembic commands ###
