"""empty message

Revision ID: 549249bc9c82
Revises: 7143ce607d42
Create Date: 2023-09-04 16:08:53.966658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549249bc9c82'
down_revision = '7143ce607d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_category', sa.String(length=150), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_column('unit')
        batch_op.drop_column('food_category_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_category_name', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.INTEGER(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('food_category')

    # ### end Alembic commands ###
