"""empty message

Revision ID: 81746abbde01
Revises: 710e3bda7244
Create Date: 2023-09-04 15:23:58.176237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81746abbde01'
down_revision = '710e3bda7244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_post_food_id_food'), 'food', ['food_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_food_id_food'), type_='foreignkey')
        batch_op.drop_column('food_id')

    # ### end Alembic commands ###
