"""empty message

Revision ID: b9266d6ffdfe
Revises: 629d6e5e7211
Create Date: 2023-09-04 09:19:52.106796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9266d6ffdfe'
down_revision = '629d6e5e7211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_liker',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_post_liker_post_id_post'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_post_liker_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name=op.f('pk_post_liker'))
    )
    op.create_table('comment_liker',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('fk_comment_liker_comment_id_comment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_comment_liker_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id', name=op.f('pk_comment_liker'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_liker')
    op.drop_table('post_liker')
    # ### end Alembic commands ###
